// Soteria's development service catalogue. This is the pricing "brain":
// every feature below has hours (effort) AND a base price (already includes
// Soteria's target margin at *standard* complexity — the project-level
// complexity multiplier from pricing-rules.ts is applied on top).
//
// PLACEHOLDER VALUES: hours/prices are reasonable starting estimates, not
// backed by logged Soteria project data yet. Once time entries exist for a
// few real projects, replace these with evidence — see docs/pricing-model.md
// §20 "Pricing intelligence".
//
// `keywords` on each feature are what the budget-fit assistant
// (lib/budget-fit.ts) matches against a pasted client brief. They're
// hand-picked, not derived from name/description — see the comment on
// FeatureDefinition in lib/types.ts for why that distinction matters.
//
// Edit this file (not components) to add, price, or retire a feature.

import { FeatureDefinition } from "@/lib/types";

export const BASE_SYSTEM_FEATURE_ID = "base-system";

export const developmentFeatures: FeatureDefinition[] = [
  // --- Always included -----------------------------------------------
  {
    id: BASE_SYSTEM_FEATURE_ID,
    category: "website",
    name: "Base system",
    description:
      "Project setup, deployment pipeline, base layout/navigation, and QA pass. Every project includes this.",
    hours: 10,
    basePrice: 500_000,
    complexity: "low",
    required: true,
  },

  // --- Website & design -------------------------------------------------
  {
    id: "web-landing-page",
    category: "website",
    name: "Landing / homepage",
    description: "Single marketing landing page with hero, sections, CTA.",
    hours: 4,
    basePrice: 120_000,
    complexity: "low",
    keywords: ["homepage", "landing page", "hero section", "hero"],
  },
  {
    id: "web-standard-page",
    category: "website",
    name: "Standard content page",
    description: "About, contact, policies, FAQ — per page.",
    hours: 2,
    basePrice: 60_000,
    complexity: "low",
    keywords: [
      "about us",
      "contact us",
      "privacy policy",
      "terms and conditions",
      "terms & conditions",
      "faq",
      "careers page",
    ],
  },
  {
    id: "web-complex-page",
    category: "website",
    name: "Complex page (custom layout/logic)",
    description: "A page requiring bespoke layout, filtering, or interactivity.",
    hours: 6,
    basePrice: 180_000,
    complexity: "medium",
    keywords: ["custom layout", "interactive page", "filtering"],
  },
  {
    id: "web-responsive",
    category: "website",
    name: "Responsive implementation",
    description: "Mobile/tablet/desktop layouts and testing across breakpoints.",
    hours: 5,
    basePrice: 100_000,
    complexity: "low",
    keywords: [
      "responsive",
      "mobile-first",
      "mobile friendly",
      "android",
      "iphone",
      "tablet",
      "works on all devices",
      "cross-device",
    ],
  },
  {
    id: "web-custom-ui",
    category: "website",
    name: "Custom UI design",
    description: "Bespoke visual design beyond a standard template.",
    hours: 12,
    basePrice: 350_000,
    complexity: "medium",
    keywords: [
      "modern design",
      "professional design",
      "high-end",
      "premium design",
      "custom design",
      "not a template",
      "bespoke",
    ],
  },
  {
    id: "web-brand-implementation",
    category: "website",
    name: "Brand implementation",
    description: "Apply existing brand guidelines (colours, type, logo usage) across the build.",
    hours: 4,
    basePrice: 90_000,
    complexity: "low",
    keywords: ["brand guidelines", "logo", "brand identity", "visual identity"],
  },
  {
    id: "web-animation",
    category: "website",
    name: "Animation / micro-interactions",
    description: "Scroll/hover/transition animation beyond framework defaults.",
    hours: 6,
    basePrice: 150_000,
    complexity: "medium",
    keywords: ["animation", "micro-interaction", "animated counter", "subtle animation"],
  },
  {
    id: "web-seo",
    category: "website",
    name: "SEO setup",
    description: "Meta tags, sitemap, structured data, basic on-page SEO.",
    hours: 3,
    basePrice: 70_000,
    complexity: "low",
    keywords: [
      "seo",
      "sitemap",
      "robots.txt",
      "meta description",
      "structured data",
      "schema markup",
      "open graph",
      "canonical url",
    ],
  },
  {
    id: "web-accessibility",
    category: "website",
    name: "Accessibility pass",
    description: "Keyboard navigation, labels, contrast checks against WCAG AA.",
    hours: 4,
    basePrice: 90_000,
    complexity: "medium",
    keywords: [
      "accessibility",
      "wcag",
      "screen reader",
      "keyboard navigation",
      "accessible",
      "color contrast",
    ],
  },

  // --- CMS ---------------------------------------------------------------
  {
    id: "cms-basic",
    category: "cms",
    name: "Basic CMS",
    description: "Editable text/image content without a full page builder.",
    hours: 8,
    basePrice: 220_000,
    complexity: "medium",
    keywords: [
      "cms",
      "content management",
      "update content",
      "edit content without a developer",
      "non-technical staff",
    ],
  },
  {
    id: "cms-advanced",
    category: "cms",
    name: "Advanced CMS",
    description: "Structured content types, relationships, versioning.",
    hours: 16,
    basePrice: 450_000,
    complexity: "high",
    keywords: ["structured content", "content versioning", "content types"],
  },
  {
    id: "cms-blog",
    category: "cms",
    name: "Blog / news",
    description: "Post listing, categories, single post view.",
    hours: 6,
    basePrice: 150_000,
    complexity: "low",
    keywords: ["blog", "news", "articles", "press releases", "news & stories"],
  },
  {
    id: "cms-media",
    category: "cms",
    name: "Media management",
    description: "Upload, organise, and reuse images/files across content.",
    hours: 5,
    basePrice: 120_000,
    complexity: "medium",
    keywords: ["media library", "upload images", "image optimization", "webp", "avif"],
  },
  {
    id: "cms-gallery",
    category: "cms",
    name: "Media gallery / albums",
    description:
      "Photo and video gallery organised into albums, with filtering (e.g. by project, category, or year).",
    hours: 8,
    basePrice: 210_000,
    complexity: "medium",
    keywords: ["gallery", "photo gallery", "video gallery", "albums", "photos and videos"],
  },
  {
    id: "cms-reports-library",
    category: "cms",
    name: "Reports & publications library",
    description:
      "Document library for downloadable files (annual reports, policies, newsletters) with title/category/year metadata.",
    hours: 6,
    basePrice: 160_000,
    complexity: "medium",
    keywords: [
      "reports & publications",
      "annual report",
      "financial report",
      "publications",
      "document library",
      "downloadable documents",
      "strategic plan",
    ],
  },
  {
    id: "cms-page-builder",
    category: "cms",
    name: "Page builder",
    description: "Drag/drop or block-based page composition for non-technical editors.",
    hours: 20,
    basePrice: 550_000,
    complexity: "high",
    keywords: ["page builder", "drag and drop", "block-based editor"],
  },
  {
    id: "cms-dashboard",
    category: "cms",
    name: "Content management dashboard",
    description: "Dedicated admin view for managing content at scale.",
    hours: 10,
    basePrice: 280_000,
    complexity: "medium",
    keywords: ["admin panel", "cms dashboard", "manage content"],
  },

  // --- Authentication ------------------------------------------------------
  {
    id: "auth-email-password",
    category: "auth",
    name: "Email/password authentication",
    description: "Sign up, log in, session handling.",
    hours: 6,
    basePrice: 150_000,
    complexity: "medium",
    keywords: ["login", "sign up", "authentication", "secure authentication", "admin login"],
  },
  {
    id: "auth-social-google",
    category: "auth",
    name: "Google login",
    description: "OAuth sign-in via Google.",
    hours: 3,
    basePrice: 80_000,
    complexity: "medium",
    dependsOn: ["auth-email-password"],
    keywords: ["google login", "sign in with google"],
  },
  {
    id: "auth-social-microsoft",
    category: "auth",
    name: "Microsoft login",
    description: "OAuth sign-in via Microsoft.",
    hours: 3,
    basePrice: 80_000,
    complexity: "medium",
    dependsOn: ["auth-email-password"],
    keywords: ["microsoft login", "sign in with microsoft"],
  },
  {
    id: "auth-magic-link",
    category: "auth",
    name: "Magic link sign-in",
    description: "Passwordless email-link authentication.",
    hours: 4,
    basePrice: 100_000,
    complexity: "medium",
    keywords: ["magic link", "passwordless"],
  },
  {
    id: "auth-password-reset",
    category: "auth",
    name: "Password reset flow",
    description: "Forgot-password email + reset flow.",
    hours: 3,
    basePrice: 70_000,
    complexity: "low",
    dependsOn: ["auth-email-password"],
    keywords: ["password reset", "forgot password"],
  },
  {
    id: "auth-mfa",
    category: "auth",
    name: "Multi-factor authentication",
    description: "SMS or app-based second factor.",
    hours: 8,
    basePrice: 220_000,
    complexity: "high",
    keywords: ["multi-factor", "two-factor", "2fa", "mfa"],
  },
  {
    id: "auth-rbac",
    category: "auth",
    name: "Role-based access control",
    description: "Distinct permission levels (e.g. admin/staff/customer).",
    hours: 10,
    basePrice: 260_000,
    complexity: "high",
    keywords: [
      "role-based access",
      "admin roles",
      "permissions",
      "super administrator",
      "finance officer",
      "program manager",
      "communications officer",
      "volunteer coordinator",
      "editor role",
    ],
  },

  // --- Commerce ------------------------------------------------------------
  {
    id: "commerce-catalogue",
    category: "commerce",
    name: "Product catalogue",
    description: "Product listing, detail pages, categories.",
    hours: 14,
    basePrice: 380_000,
    complexity: "medium",
    keywords: ["product catalogue", "product listing", "shop products"],
  },
  {
    id: "commerce-variants",
    category: "commerce",
    name: "Product variants",
    description: "Size/colour/option combinations with variant-level stock and price.",
    hours: 8,
    basePrice: 200_000,
    complexity: "high",
    dependsOn: ["commerce-catalogue"],
    keywords: ["product variants", "size and colour options"],
  },
  {
    id: "commerce-cart-checkout",
    category: "commerce",
    name: "Cart & checkout",
    description: "Cart management and checkout flow (excludes payment gateway integration).",
    hours: 16,
    basePrice: 420_000,
    complexity: "high",
    dependsOn: ["commerce-catalogue"],
    keywords: ["cart", "checkout", "shopping cart"],
  },
  {
    id: "commerce-orders",
    category: "commerce",
    name: "Order management",
    description: "Order records, statuses, history for staff and customers.",
    hours: 10,
    basePrice: 260_000,
    complexity: "medium",
    dependsOn: ["commerce-cart-checkout"],
    keywords: ["order management", "order history", "order status"],
  },
  {
    id: "commerce-customer-accounts",
    category: "commerce",
    name: "Customer accounts",
    description: "Customer profile, order history, saved details.",
    hours: 6,
    basePrice: 160_000,
    complexity: "medium",
    keywords: ["customer accounts", "customer profile"],
  },
  {
    id: "commerce-reviews",
    category: "commerce",
    name: "Reviews & ratings",
    description: "Customer reviews with moderation.",
    hours: 6,
    basePrice: 140_000,
    complexity: "medium",
    keywords: ["reviews", "ratings", "testimonials on products"],
  },
  {
    id: "commerce-wishlist",
    category: "commerce",
    name: "Wishlist",
    description: "Save-for-later product lists.",
    hours: 3,
    basePrice: 70_000,
    complexity: "low",
    keywords: ["wishlist", "save for later"],
  },
  {
    id: "commerce-coupons",
    category: "commerce",
    name: "Coupons & discounts",
    description: "Percentage/fixed discount codes with usage rules.",
    hours: 6,
    basePrice: 150_000,
    complexity: "medium",
    keywords: ["coupons", "discount codes", "promo codes"],
  },
  {
    id: "commerce-gift-cards",
    category: "commerce",
    name: "Gift cards",
    description: "Purchasable, redeemable gift card balances.",
    hours: 8,
    basePrice: 200_000,
    complexity: "high",
    keywords: ["gift cards"],
  },
  {
    id: "commerce-donations",
    category: "commerce",
    name: "Donation / fundraising system",
    description:
      "One-time and custom-amount donation collection with per-project or per-campaign funding progress (raised/target/percentage).",
    hours: 16,
    basePrice: 450_000,
    complexity: "high",
    dependsOn: ["int-payment-gateway"],
    keywords: [
      "donation",
      "donate",
      "donate now",
      "fundraising",
      "funding goal",
      "amount raised",
      "support this project",
      "donation system",
    ],
  },
  {
    id: "commerce-recurring-donations",
    category: "commerce",
    name: "Recurring / monthly donations",
    description: "Subscription-style recurring donations with management for the donor.",
    hours: 10,
    basePrice: 260_000,
    complexity: "high",
    dependsOn: ["commerce-donations"],
    keywords: ["monthly donation", "recurring donation", "manage recurring donations"],
  },

  // --- Engagement (donors, volunteers, community) --------------------------
  {
    id: "engagement-donor-portal",
    category: "engagement",
    name: "Donor portal",
    description:
      "Donor account area: donation history, downloadable receipts, supported projects, communication preferences.",
    hours: 14,
    basePrice: 380_000,
    complexity: "high",
    dependsOn: ["auth-email-password", "commerce-donations"],
    keywords: [
      "donor portal",
      "donor account",
      "donation history",
      "download receipts",
      "manage recurring donations",
    ],
  },
  {
    id: "engagement-volunteer-system",
    category: "engagement",
    name: "Volunteer application system",
    description:
      "Volunteer registration form plus an admin pipeline for reviewing applications (new → shortlisted → accepted, etc.).",
    hours: 10,
    basePrice: 260_000,
    complexity: "medium",
    keywords: [
      "volunteer",
      "volunteer registration",
      "volunteer application",
      "volunteer coordinator",
      "application status",
    ],
  },
  {
    id: "engagement-events",
    category: "engagement",
    name: "Events with registration",
    description: "Event listings with date/location/description and visitor registration/RSVP.",
    hours: 10,
    basePrice: 260_000,
    complexity: "medium",
    keywords: ["events", "event registration", "rsvp", "event calendar"],
  },
  {
    id: "engagement-testimonials",
    category: "engagement",
    name: "Success stories / testimonials",
    description:
      "Structured story entries (beneficiary, before/after, photo/video, program) with a story detail page.",
    hours: 6,
    basePrice: 150_000,
    complexity: "medium",
    keywords: [
      "success stories",
      "stories of change",
      "testimonials",
      "before/after",
      "video testimonial",
      "beneficiary story",
    ],
  },
  {
    id: "engagement-newsletter",
    category: "engagement",
    name: "Newsletter subscription",
    description: "Subscribe/unsubscribe with consent and email verification, plus admin subscriber management.",
    hours: 5,
    basePrice: 120_000,
    complexity: "medium",
    dependsOn: ["int-email"],
    keywords: ["newsletter", "subscribe", "email subscription", "subscriber management"],
  },
  {
    id: "engagement-contact-inbox",
    category: "engagement",
    name: "Contact / inquiry inbox",
    description:
      "Admin inbox consolidating contact, partnership, and general inquiries with a status pipeline (new/read/in progress/resolved).",
    hours: 6,
    basePrice: 160_000,
    complexity: "medium",
    keywords: [
      "contact management",
      "inquiry inbox",
      "partnership inquiry",
      "contact messages",
      "complaints",
      "feedback",
    ],
  },

  // --- Business management --------------------------------------------------
  {
    id: "biz-inventory",
    category: "business-management",
    name: "Inventory management",
    description: "Stock levels, adjustments, low-stock indicators.",
    hours: 14,
    basePrice: 380_000,
    complexity: "high",
    keywords: ["inventory", "stock levels", "low-stock"],
  },
  {
    id: "biz-purchases-suppliers",
    category: "business-management",
    name: "Purchases & suppliers",
    description: "Supplier records and purchase order tracking.",
    hours: 10,
    basePrice: 260_000,
    complexity: "medium",
    keywords: ["suppliers", "purchase orders"],
  },
  {
    id: "biz-sales-tracking",
    category: "business-management",
    name: "Sales tracking",
    description: "Sales records outside of e-commerce checkout (e.g. in-person/manual sales).",
    hours: 8,
    basePrice: 220_000,
    complexity: "medium",
    keywords: ["sales tracking", "manual sales"],
  },
  {
    id: "biz-expenses",
    category: "business-management",
    name: "Expense tracking",
    description: "Record and categorise business expenses.",
    hours: 6,
    basePrice: 160_000,
    complexity: "medium",
    keywords: ["expense tracking", "expenses"],
  },
  {
    id: "biz-reports",
    category: "business-management",
    name: "Reports",
    description: "Exportable summary reports (sales, stock, revenue).",
    hours: 10,
    basePrice: 260_000,
    complexity: "medium",
    keywords: [
      "reports",
      "dashboard reports",
      "export to pdf",
      "export to excel",
      "export to csv",
      "donations by month",
      "donations by project",
    ],
  },
  {
    id: "biz-dashboard",
    category: "business-management",
    name: "Admin dashboard",
    description: "At-a-glance operational overview for staff/admins.",
    hours: 12,
    basePrice: 320_000,
    complexity: "medium",
    keywords: ["admin dashboard", "operational overview", "charts and graphs", "dashboard reports"],
  },
  {
    id: "biz-staff-management",
    category: "business-management",
    name: "Staff management",
    description: "Staff records, roles, and activity visibility.",
    hours: 8,
    basePrice: 210_000,
    complexity: "medium",
    dependsOn: ["auth-rbac"],
    keywords: ["staff management", "team management"],
  },

  // --- Integrations ----------------------------------------------------------
  {
    id: "int-payment-gateway",
    category: "integrations",
    name: "Payment gateway integration",
    description: "Card/mobile money payment integration incl. webhook handling and testing.",
    hours: 20,
    basePrice: 550_000,
    complexity: "high",
    notes: "Historically underestimated — see docs/pricing-model.md before quoting a tight deadline.",
    keywords: ["payment gateway", "visa", "mastercard", "paypal", "card payments", "secure payment"],
  },
  {
    id: "int-mobile-money",
    category: "integrations",
    name: "Mobile money (MTN/Airtel)",
    description: "Mobile money collection integration.",
    hours: 14,
    basePrice: 400_000,
    complexity: "high",
    keywords: ["mtn mobile money", "airtel money", "mobile money"],
  },
  {
    id: "int-email",
    category: "integrations",
    name: "Transactional email",
    description: "Order confirmations, notifications, password resets via email provider.",
    hours: 5,
    basePrice: 120_000,
    complexity: "medium",
    keywords: [
      "transactional email",
      "confirmation email",
      "email notifications",
      "email templates",
      "donation confirmation email",
    ],
  },
  {
    id: "int-sms",
    category: "integrations",
    name: "SMS notifications",
    description: "Transactional SMS via an SMS gateway.",
    hours: 6,
    basePrice: 150_000,
    complexity: "medium",
    keywords: ["sms", "sms notifications", "text message notifications"],
  },
  {
    id: "int-whatsapp",
    category: "integrations",
    name: "WhatsApp notifications",
    description: "Order/status updates via WhatsApp Business API.",
    hours: 8,
    basePrice: 220_000,
    complexity: "high",
    keywords: ["whatsapp", "whatsapp button", "whatsapp business"],
  },
  {
    id: "int-maps",
    category: "integrations",
    name: "Maps / location",
    description: "Address lookup or map display integration.",
    hours: 5,
    basePrice: 130_000,
    complexity: "medium",
    keywords: ["google maps", "location map", "map integration"],
  },
  {
    id: "int-analytics",
    category: "integrations",
    name: "Analytics integration",
    description: "Event/conversion tracking setup (e.g. GA4, Meta Pixel).",
    hours: 3,
    basePrice: 80_000,
    complexity: "low",
    keywords: ["analytics", "google analytics", "ga4", "meta pixel", "traffic sources", "conversion tracking"],
  },
  {
    id: "int-shipping",
    category: "integrations",
    name: "Shipping / logistics integration",
    description: "Rate lookup or fulfilment integration with a delivery provider.",
    hours: 10,
    basePrice: 280_000,
    complexity: "high",
    keywords: ["shipping", "delivery integration", "logistics"],
  },
  {
    id: "int-accounting",
    category: "integrations",
    name: "Accounting system integration",
    description: "Sync invoices/payments to an external bookkeeping tool.",
    hours: 14,
    basePrice: 400_000,
    complexity: "high",
    keywords: ["accounting integration", "bookkeeping sync"],
  },
  {
    id: "int-backup",
    category: "integrations",
    name: "Automated backups",
    description: "Scheduled backups of the database and uploaded media/documents, stored separately from the primary server.",
    hours: 4,
    basePrice: 110_000,
    complexity: "medium",
    keywords: ["backups", "automatic backups", "database backup", "disaster recovery"],
  },
  {
    id: "int-external-api",
    category: "integrations",
    name: "External API integration (generic)",
    description: "Per additional third-party API not covered above.",
    hours: 10,
    basePrice: 260_000,
    complexity: "high",
    keywords: ["third-party api", "external integration"],
  },

  // --- AI --------------------------------------------------------------------
  {
    id: "ai-content-generation",
    category: "ai",
    name: "AI content generation",
    description: "AI-assisted copy generation tooling inside the admin experience.",
    hours: 10,
    basePrice: 280_000,
    complexity: "high",
    keywords: ["ai content generation", "ai-assisted content"],
  },
  {
    id: "ai-product-descriptions",
    category: "ai",
    name: "AI product descriptions",
    description: "Generate draft product descriptions from structured data.",
    hours: 6,
    basePrice: 180_000,
    complexity: "medium",
    keywords: ["ai product descriptions"],
  },
  {
    id: "ai-chatbot",
    category: "ai",
    name: "AI chatbot / assistant",
    description: "Customer-facing conversational assistant.",
    hours: 24,
    basePrice: 700_000,
    complexity: "high",
    keywords: ["chatbot", "ai assistant", "conversational assistant"],
  },
  {
    id: "ai-recommendations",
    category: "ai",
    name: "AI recommendations",
    description: "Product/content recommendation logic.",
    hours: 18,
    basePrice: 500_000,
    complexity: "high",
    keywords: ["ai recommendations", "recommendation engine"],
  },
  {
    id: "ai-analytics",
    category: "ai",
    name: "AI-assisted analytics",
    description: "Natural-language summaries over business data.",
    hours: 14,
    basePrice: 400_000,
    complexity: "high",
    keywords: ["ai-assisted analytics", "ai insights"],
  },
  {
    id: "ai-image-generation",
    category: "ai",
    name: "AI image generation",
    description: "Generated imagery tooling inside the product.",
    hours: 8,
    basePrice: 240_000,
    complexity: "medium",
    keywords: ["ai image generation"],
  },

  // --- Advanced ----------------------------------------------------------------
  {
    id: "adv-notifications",
    category: "advanced",
    name: "In-app notifications",
    description: "In-product notification centre/feed.",
    hours: 8,
    basePrice: 210_000,
    complexity: "medium",
    keywords: [
      "notifications",
      "admin notifications",
      "new donation notification",
      "new volunteer application notification",
    ],
  },
  {
    id: "adv-search",
    category: "advanced",
    name: "Site-wide search",
    description: "Search across multiple content types (e.g. news, projects, programs, reports, FAQs) with relevance ranking.",
    hours: 6,
    basePrice: 170_000,
    complexity: "medium",
    keywords: ["site search", "global search", "search functionality"],
  },
  {
    id: "adv-audit-log",
    category: "advanced",
    name: "Admin activity / audit log",
    description: "Records who changed what and when across admin actions.",
    hours: 5,
    basePrice: 140_000,
    complexity: "medium",
    keywords: ["audit log", "activity log", "admin activity logs", "every administrator action should be logged"],
  },
  {
    id: "adv-api-integration",
    category: "advanced",
    name: "Public API for this project",
    description: "Expose an API for the client's own downstream use.",
    hours: 14,
    basePrice: 400_000,
    complexity: "high",
    keywords: ["public api", "rest api", "graphql api", "api documentation"],
  },
  {
    id: "adv-multi-language",
    category: "advanced",
    name: "Multi-language support",
    description: "i18n scaffolding and translated content for 2+ languages.",
    hours: 10,
    basePrice: 280_000,
    complexity: "high",
    keywords: ["multi-language", "multilingual", "translations", "i18n"],
  },
];

export function getFeatureById(id: string): FeatureDefinition | undefined {
  return developmentFeatures.find((f) => f.id === id);
}
