// Soteria's development service catalogue. This is the pricing "brain":
// every feature below has hours (effort) AND a base price (already includes
// Soteria's target margin at *standard* complexity — the project-level
// complexity multiplier from pricing-rules.ts is applied on top).
//
// PLACEHOLDER VALUES: hours/prices are reasonable starting estimates, not
// backed by logged Soteria project data yet. Once time entries exist for a
// few real projects, replace these with evidence — see docs/pricing-model.md
// §20 "Pricing intelligence".
//
// Edit this file (not components) to add, price, or retire a feature.

import { FeatureDefinition } from "@/lib/types";

export const BASE_SYSTEM_FEATURE_ID = "base-system";

export const developmentFeatures: FeatureDefinition[] = [
  // --- Always included -----------------------------------------------
  {
    id: BASE_SYSTEM_FEATURE_ID,
    category: "website",
    name: "Base system",
    description:
      "Project setup, deployment pipeline, base layout/navigation, and QA pass. Every project includes this.",
    hours: 10,
    basePrice: 500_000,
    complexity: "low",
    required: true,
  },

  // --- Website & design -------------------------------------------------
  {
    id: "web-landing-page",
    category: "website",
    name: "Landing / homepage",
    description: "Single marketing landing page with hero, sections, CTA.",
    hours: 4,
    basePrice: 120_000,
    complexity: "low",
  },
  {
    id: "web-standard-page",
    category: "website",
    name: "Standard content page",
    description: "About, contact, policies, FAQ — per page.",
    hours: 2,
    basePrice: 60_000,
    complexity: "low",
  },
  {
    id: "web-complex-page",
    category: "website",
    name: "Complex page (custom layout/logic)",
    description: "A page requiring bespoke layout, filtering, or interactivity.",
    hours: 6,
    basePrice: 180_000,
    complexity: "medium",
  },
  {
    id: "web-responsive",
    category: "website",
    name: "Responsive implementation",
    description: "Mobile/tablet/desktop layouts and testing across breakpoints.",
    hours: 5,
    basePrice: 100_000,
    complexity: "low",
  },
  {
    id: "web-custom-ui",
    category: "website",
    name: "Custom UI design",
    description: "Bespoke visual design beyond a standard template.",
    hours: 12,
    basePrice: 350_000,
    complexity: "medium",
  },
  {
    id: "web-brand-implementation",
    category: "website",
    name: "Brand implementation",
    description: "Apply existing brand guidelines (colours, type, logo usage) across the build.",
    hours: 4,
    basePrice: 90_000,
    complexity: "low",
  },
  {
    id: "web-animation",
    category: "website",
    name: "Animation / micro-interactions",
    description: "Scroll/hover/transition animation beyond framework defaults.",
    hours: 6,
    basePrice: 150_000,
    complexity: "medium",
  },
  {
    id: "web-seo",
    category: "website",
    name: "SEO setup",
    description: "Meta tags, sitemap, structured data, basic on-page SEO.",
    hours: 3,
    basePrice: 70_000,
    complexity: "low",
  },
  {
    id: "web-accessibility",
    category: "website",
    name: "Accessibility pass",
    description: "Keyboard navigation, labels, contrast checks against WCAG AA.",
    hours: 4,
    basePrice: 90_000,
    complexity: "medium",
  },

  // --- CMS ---------------------------------------------------------------
  {
    id: "cms-basic",
    category: "cms",
    name: "Basic CMS",
    description: "Editable text/image content without a full page builder.",
    hours: 8,
    basePrice: 220_000,
    complexity: "medium",
  },
  {
    id: "cms-advanced",
    category: "cms",
    name: "Advanced CMS",
    description: "Structured content types, relationships, versioning.",
    hours: 16,
    basePrice: 450_000,
    complexity: "high",
  },
  {
    id: "cms-blog",
    category: "cms",
    name: "Blog / news",
    description: "Post listing, categories, single post view.",
    hours: 6,
    basePrice: 150_000,
    complexity: "low",
  },
  {
    id: "cms-media",
    category: "cms",
    name: "Media management",
    description: "Upload, organise, and reuse images/files across content.",
    hours: 5,
    basePrice: 120_000,
    complexity: "medium",
  },
  {
    id: "cms-page-builder",
    category: "cms",
    name: "Page builder",
    description: "Drag/drop or block-based page composition for non-technical editors.",
    hours: 20,
    basePrice: 550_000,
    complexity: "high",
  },
  {
    id: "cms-dashboard",
    category: "cms",
    name: "Content management dashboard",
    description: "Dedicated admin view for managing content at scale.",
    hours: 10,
    basePrice: 280_000,
    complexity: "medium",
  },

  // --- Authentication ------------------------------------------------------
  {
    id: "auth-email-password",
    category: "auth",
    name: "Email/password authentication",
    description: "Sign up, log in, session handling.",
    hours: 6,
    basePrice: 150_000,
    complexity: "medium",
  },
  {
    id: "auth-social-google",
    category: "auth",
    name: "Google login",
    description: "OAuth sign-in via Google.",
    hours: 3,
    basePrice: 80_000,
    complexity: "medium",
    dependsOn: ["auth-email-password"],
  },
  {
    id: "auth-social-microsoft",
    category: "auth",
    name: "Microsoft login",
    description: "OAuth sign-in via Microsoft.",
    hours: 3,
    basePrice: 80_000,
    complexity: "medium",
    dependsOn: ["auth-email-password"],
  },
  {
    id: "auth-magic-link",
    category: "auth",
    name: "Magic link sign-in",
    description: "Passwordless email-link authentication.",
    hours: 4,
    basePrice: 100_000,
    complexity: "medium",
  },
  {
    id: "auth-password-reset",
    category: "auth",
    name: "Password reset flow",
    description: "Forgot-password email + reset flow.",
    hours: 3,
    basePrice: 70_000,
    complexity: "low",
    dependsOn: ["auth-email-password"],
  },
  {
    id: "auth-mfa",
    category: "auth",
    name: "Multi-factor authentication",
    description: "SMS or app-based second factor.",
    hours: 8,
    basePrice: 220_000,
    complexity: "high",
  },
  {
    id: "auth-rbac",
    category: "auth",
    name: "Role-based access control",
    description: "Distinct permission levels (e.g. admin/staff/customer).",
    hours: 10,
    basePrice: 260_000,
    complexity: "high",
  },

  // --- Commerce ------------------------------------------------------------
  {
    id: "commerce-catalogue",
    category: "commerce",
    name: "Product catalogue",
    description: "Product listing, detail pages, categories.",
    hours: 14,
    basePrice: 380_000,
    complexity: "medium",
  },
  {
    id: "commerce-variants",
    category: "commerce",
    name: "Product variants",
    description: "Size/colour/option combinations with variant-level stock and price.",
    hours: 8,
    basePrice: 200_000,
    complexity: "high",
    dependsOn: ["commerce-catalogue"],
  },
  {
    id: "commerce-cart-checkout",
    category: "commerce",
    name: "Cart & checkout",
    description: "Cart management and checkout flow (excludes payment gateway integration).",
    hours: 16,
    basePrice: 420_000,
    complexity: "high",
    dependsOn: ["commerce-catalogue"],
  },
  {
    id: "commerce-orders",
    category: "commerce",
    name: "Order management",
    description: "Order records, statuses, history for staff and customers.",
    hours: 10,
    basePrice: 260_000,
    complexity: "medium",
    dependsOn: ["commerce-cart-checkout"],
  },
  {
    id: "commerce-customer-accounts",
    category: "commerce",
    name: "Customer accounts",
    description: "Customer profile, order history, saved details.",
    hours: 6,
    basePrice: 160_000,
    complexity: "medium",
  },
  {
    id: "commerce-reviews",
    category: "commerce",
    name: "Reviews & ratings",
    description: "Customer reviews with moderation.",
    hours: 6,
    basePrice: 140_000,
    complexity: "medium",
  },
  {
    id: "commerce-wishlist",
    category: "commerce",
    name: "Wishlist",
    description: "Save-for-later product lists.",
    hours: 3,
    basePrice: 70_000,
    complexity: "low",
  },
  {
    id: "commerce-coupons",
    category: "commerce",
    name: "Coupons & discounts",
    description: "Percentage/fixed discount codes with usage rules.",
    hours: 6,
    basePrice: 150_000,
    complexity: "medium",
  },
  {
    id: "commerce-gift-cards",
    category: "commerce",
    name: "Gift cards",
    description: "Purchasable, redeemable gift card balances.",
    hours: 8,
    basePrice: 200_000,
    complexity: "high",
  },

  // --- Business management --------------------------------------------------
  {
    id: "biz-inventory",
    category: "business-management",
    name: "Inventory management",
    description: "Stock levels, adjustments, low-stock indicators.",
    hours: 14,
    basePrice: 380_000,
    complexity: "high",
  },
  {
    id: "biz-purchases-suppliers",
    category: "business-management",
    name: "Purchases & suppliers",
    description: "Supplier records and purchase order tracking.",
    hours: 10,
    basePrice: 260_000,
    complexity: "medium",
  },
  {
    id: "biz-sales-tracking",
    category: "business-management",
    name: "Sales tracking",
    description: "Sales records outside of e-commerce checkout (e.g. in-person/manual sales).",
    hours: 8,
    basePrice: 220_000,
    complexity: "medium",
  },
  {
    id: "biz-expenses",
    category: "business-management",
    name: "Expense tracking",
    description: "Record and categorise business expenses.",
    hours: 6,
    basePrice: 160_000,
    complexity: "medium",
  },
  {
    id: "biz-reports",
    category: "business-management",
    name: "Reports",
    description: "Exportable summary reports (sales, stock, revenue).",
    hours: 10,
    basePrice: 260_000,
    complexity: "medium",
  },
  {
    id: "biz-dashboard",
    category: "business-management",
    name: "Admin dashboard",
    description: "At-a-glance operational overview for staff/admins.",
    hours: 12,
    basePrice: 320_000,
    complexity: "medium",
  },
  {
    id: "biz-staff-management",
    category: "business-management",
    name: "Staff management",
    description: "Staff records, roles, and activity visibility.",
    hours: 8,
    basePrice: 210_000,
    complexity: "medium",
    dependsOn: ["auth-rbac"],
  },

  // --- Integrations ----------------------------------------------------------
  {
    id: "int-payment-gateway",
    category: "integrations",
    name: "Payment gateway integration",
    description: "Card/mobile money payment integration incl. webhook handling and testing.",
    hours: 20,
    basePrice: 550_000,
    complexity: "high",
    notes: "Historically underestimated — see docs/pricing-model.md before quoting a tight deadline.",
  },
  {
    id: "int-mobile-money",
    category: "integrations",
    name: "Mobile money (MTN/Airtel)",
    description: "Mobile money collection integration.",
    hours: 14,
    basePrice: 400_000,
    complexity: "high",
  },
  {
    id: "int-email",
    category: "integrations",
    name: "Transactional email",
    description: "Order confirmations, notifications, password resets via email provider.",
    hours: 5,
    basePrice: 120_000,
    complexity: "medium",
  },
  {
    id: "int-sms",
    category: "integrations",
    name: "SMS notifications",
    description: "Transactional SMS via an SMS gateway.",
    hours: 6,
    basePrice: 150_000,
    complexity: "medium",
  },
  {
    id: "int-whatsapp",
    category: "integrations",
    name: "WhatsApp notifications",
    description: "Order/status updates via WhatsApp Business API.",
    hours: 8,
    basePrice: 220_000,
    complexity: "high",
  },
  {
    id: "int-maps",
    category: "integrations",
    name: "Maps / location",
    description: "Address lookup or map display integration.",
    hours: 5,
    basePrice: 130_000,
    complexity: "medium",
  },
  {
    id: "int-analytics",
    category: "integrations",
    name: "Analytics integration",
    description: "Event/conversion tracking setup (e.g. GA4, Meta Pixel).",
    hours: 3,
    basePrice: 80_000,
    complexity: "low",
  },
  {
    id: "int-shipping",
    category: "integrations",
    name: "Shipping / logistics integration",
    description: "Rate lookup or fulfilment integration with a delivery provider.",
    hours: 10,
    basePrice: 280_000,
    complexity: "high",
  },
  {
    id: "int-accounting",
    category: "integrations",
    name: "Accounting system integration",
    description: "Sync invoices/payments to an external bookkeeping tool.",
    hours: 14,
    basePrice: 400_000,
    complexity: "high",
  },
  {
    id: "int-external-api",
    category: "integrations",
    name: "External API integration (generic)",
    description: "Per additional third-party API not covered above.",
    hours: 10,
    basePrice: 260_000,
    complexity: "high",
  },

  // --- AI --------------------------------------------------------------------
  {
    id: "ai-content-generation",
    category: "ai",
    name: "AI content generation",
    description: "AI-assisted copy generation tooling inside the admin experience.",
    hours: 10,
    basePrice: 280_000,
    complexity: "high",
  },
  {
    id: "ai-product-descriptions",
    category: "ai",
    name: "AI product descriptions",
    description: "Generate draft product descriptions from structured data.",
    hours: 6,
    basePrice: 180_000,
    complexity: "medium",
  },
  {
    id: "ai-chatbot",
    category: "ai",
    name: "AI chatbot / assistant",
    description: "Customer-facing conversational assistant.",
    hours: 24,
    basePrice: 700_000,
    complexity: "high",
  },
  {
    id: "ai-recommendations",
    category: "ai",
    name: "AI recommendations",
    description: "Product/content recommendation logic.",
    hours: 18,
    basePrice: 500_000,
    complexity: "high",
  },
  {
    id: "ai-analytics",
    category: "ai",
    name: "AI-assisted analytics",
    description: "Natural-language summaries over business data.",
    hours: 14,
    basePrice: 400_000,
    complexity: "high",
  },
  {
    id: "ai-image-generation",
    category: "ai",
    name: "AI image generation",
    description: "Generated imagery tooling inside the product.",
    hours: 8,
    basePrice: 240_000,
    complexity: "medium",
  },

  // --- Advanced ----------------------------------------------------------------
  {
    id: "adv-notifications",
    category: "advanced",
    name: "In-app notifications",
    description: "In-product notification centre/feed.",
    hours: 8,
    basePrice: 210_000,
    complexity: "medium",
  },
  {
    id: "adv-api-integration",
    category: "advanced",
    name: "Public API for this project",
    description: "Expose an API for the client's own downstream use.",
    hours: 14,
    basePrice: 400_000,
    complexity: "high",
  },
  {
    id: "adv-multi-language",
    category: "advanced",
    name: "Multi-language support",
    description: "i18n scaffolding and translated content for 2+ languages.",
    hours: 10,
    basePrice: 280_000,
    complexity: "high",
  },
];

export function getFeatureById(id: string): FeatureDefinition | undefined {
  return developmentFeatures.find((f) => f.id === id);
}
